export const testimonials = [
  {
    name: "Sophia Carter",
    role: "Designer",
    avatar: "https://dicebear.com",
    text: "I met both friends and collaborators here. It feels intentional.",
  },
  {
    name: "Marcus Lee",
    role: "Product Manager",
    avatar: "https://dicebear.com",
    text: "The conversations feel real instead of forced.",
  },
  {
    name: "Ava Brooks",
    role: "Entrepreneur",
    avatar: "https://dicebear.com",
    text: "Poly helped me start conversations naturally.",
  },
  {
    name: "Elena Rostova",
    role: "Software Engineer",
    avatar: "https://dicebear.com",
    text: "No endless scrolling, just pure, high-quality interactions.",
  },
  {
    name: "David Kim",
    role: "Data Scientist",
    avatar: "https://dicebear.com",
    text: "The community algorithm connects you on genuine shared interests.",
  },
  {
    name: "Chloe Harrison",
    role: "Content Creator",
    avatar: "https://dicebear.com",
    text: "I found my core creative circle within the first week.",
  },
  {
    name: "Tariq Mahmood",
    role: "UX Researcher",
    avatar: "https://dicebear.com",
    text: "It bypasses superficial small talk. Conversations hit deep immediately.",
  },
  {
    name: "Olivia Martinez",
    role: "Marketing Director",
    avatar: "https://dicebear.com",
    text: "Poly redefined how I network. It feels like a cozy dinner party.",
  },
  {
    name: "Liam O'Connor",
    role: "DevOps Engineer",
    avatar: "https://dicebear.com",
    text: "A refreshing space filled with deeply curious people.",
  },
  {
    name: "Aisha Diallo",
    role: "Creative Director",
    avatar: "https://dicebear.com",
    text: "The energy here is collaborative rather than competitive.",
  },
  {
    name: "Lucas Silva",
    role: "Growth Hacker",
    avatar: "https://dicebear.com",
    text: "I’ve made more meaningful professional ties here than on LinkedIn.",
  },
  {
    name: "Emma Watson",
    role: "Journalist",
    avatar: "https://dicebear.com",
    text: "Poly attracted exactly the kind of open-minded thinkers I needed.",
  },
  {
    name: "Julian Chen",
    role: "Architect",
    avatar: "https://dicebear.com",
    text: "An incredible bridge between digital connection and real-world synergy.",
  },
  {
    name: "Maya Lin",
    role: "Illustrator",
    avatar: "https://dicebear.com",
    text: "It is a breath of fresh air for introverts trying to connect.",
  },
  {
    name: "Ethan Wright",
    role: "Founder",
    avatar: "https://dicebear.com",
    text: "I met my current co-founder here. The chemistry was instant.",
  },
  {
    name: "Zara Ahmed",
    role: "Product Designer",
    avatar: "https://dicebear.com",
    text: "The crowd here actually listens. Every interaction is valuable.",
  },
  {
    name: "Noah Becker",
    role: "AI Researcher",
    avatar: "https://dicebear.com",
    text: "Intellectually stimulating conversations are the norm, not the exception.",
  },
  {
    name: "Sofia Rossi",
    role: "Community Manager",
    avatar: "https://dicebear.com",
    text: "Poly cracked the code on online psychological safety and warmth.",
  },
  {
    name: "James Tanaka",
    role: "Full Stack Developer",
    avatar: "https://dicebear.com",
    text: "Every conversation feels like an investment in my personal growth.",
  },
  {
    name: "Amara Okafor",
    role: "Strategist",
    avatar: "https://dicebear.com",
    text: "It strips away the ego and leaves room for authentic discovery.",
  },
  {
    name: "Mateo Fernandez",
    role: "Motion Designer",
    avatar: "https://dicebear.com",
    text: "I came for professional networking, but stayed for the lifelong friends.",
  },
  {
    name: "Lily Dubois",
    role: "Writer",
    avatar: "https://dicebear.com",
    text: "Poly is where I go when I want to escape social media noise.",
  },
  {
    name: "Ryan Gallagher",
    role: "Venture Capitalist",
    avatar: "https://dicebear.com",
    text: "The caliber of talent and depth of thought here is unmatched.",
  },
  {
    name: "Nina Patel",
    role: "Brand Strategist",
    avatar: "https://dicebear.com",
    text: "It focuses beautifully on intentionality over sheer numbers.",
  },
  {
    name: "Leo Dupont",
    role: "Systems Architect",
    avatar: "https://dicebear.com",
    text: "Finally, an online platform that respects human nuance.",
  },
  {
    name: "Hana Nguyen",
    role: "Frontend Engineer",
    avatar: "https://dicebear.com",
    text: "The vibe is warm, inviting, and sparky all at once.",
  },
  {
    name: "Gabriel Mendoza",
    role: "Creative Producer",
    avatar: "https://dicebear.com",
    text: "Poly curated a digital neighborhood I never want to leave.",
  },
  {
    name: "Isla Campbell",
    role: "Consultant",
    avatar: "https://dicebear.com",
    text: "It feels less like an app and more like a great community.",
  },
];
