export const testimonials = [
  {
    name: "Sarah Kim",
    role: "Product Designer",
    avatar: "https://randomuser.me/api/portraits/women/1.jpg",
    text: "Poly introduced me to people who genuinely share my interests.",
  },
  {
    name: "Daniel Okello",
    role: "Software Engineer",
    avatar: "https://randomuser.me/api/portraits/men/2.jpg",
    text: "The conversations feel meaningful from the very first message.",
  },
  {
    name: "Amina Hassan",
    role: "Photographer",
    avatar: "https://randomuser.me/api/portraits/women/3.jpg",
    text: "I found both creative collaborators and close friends here.",
  },
  {
    name: "Michael Carter",
    role: "Startup Founder",
    avatar: "https://randomuser.me/api/portraits/men/4.jpg",
    text: "It's refreshing to meet people beyond surface-level profiles.",
  },
  {
    name: "Grace Nansubuga",
    role: "Content Creator",
    avatar: "https://randomuser.me/api/portraits/women/5.jpg",
    text: "The community feels welcoming, thoughtful, and authentic.",
  },
  {
    name: "Ethan Brooks",
    role: "UX Researcher",
    avatar: "https://randomuser.me/api/portraits/men/6.jpg",
    text: "Every connection feels intentional rather than random.",
  },
  {
    name: "Sophia Martinez",
    role: "Marketing Specialist",
    avatar: "https://randomuser.me/api/portraits/women/7.jpg",
    text: "I met people here who quickly became trusted friends.",
  },
  {
    name: "James Walker",
    role: "Data Analyst",
    avatar: "https://randomuser.me/api/portraits/men/8.jpg",
    text: "The quality of conversations surprised me in the best way.",
  },
  {
    name: "Priya Patel",
    role: "Entrepreneur",
    avatar: "https://randomuser.me/api/portraits/women/9.jpg",
    text: "Poly made networking feel human again.",
  },
  {
    name: "David Chen",
    role: "Full Stack Developer",
    avatar: "https://randomuser.me/api/portraits/men/10.jpg",
    text: "I found collaborators for projects I care deeply about.",
  },
  {
    name: "Olivia Johnson",
    role: "Writer",
    avatar: "https://randomuser.me/api/portraits/women/11.jpg",
    text: "Meaningful conversations happen naturally here.",
  },
  {
    name: "Samuel Mwangi",
    role: "Business Consultant",
    avatar: "https://randomuser.me/api/portraits/men/12.jpg",
    text: "The platform attracts thoughtful and curious people.",
  },
  {
    name: "Emily Rodriguez",
    role: "Illustrator",
    avatar: "https://randomuser.me/api/portraits/women/13.jpg",
    text: "I've built friendships that extend beyond the app.",
  },
  {
    name: "Noah Thompson",
    role: "AI Engineer",
    avatar: "https://randomuser.me/api/portraits/men/14.jpg",
    text: "This is the first community platform that felt genuine.",
  },
  {
    name: "Fatima Ahmed",
    role: "Community Builder",
    avatar: "https://randomuser.me/api/portraits/women/15.jpg",
    text: "People here are open, kind, and easy to connect with.",
  },
  {
    name: "Lucas Silva",
    role: "Growth Strategist",
    avatar: "https://randomuser.me/api/portraits/men/16.jpg",
    text: "Poly helped me grow both personally and professionally.",
  },
  {
    name: "Mia Taylor",
    role: "Video Creator",
    avatar: "https://randomuser.me/api/portraits/women/17.jpg",
    text: "I immediately felt comfortable sharing ideas here.",
  },
  {
    name: "Benjamin Clark",
    role: "Architect",
    avatar: "https://randomuser.me/api/portraits/men/18.jpg",
    text: "The experience feels curated without feeling restrictive.",
  },
  {
    name: "Leah Williams",
    role: "Psychology Student",
    avatar: "https://randomuser.me/api/portraits/women/19.jpg",
    text: "I appreciate how easy it is to meet like-minded people.",
  },
  {
    name: "Jonathan Reed",
    role: "Product Manager",
    avatar: "https://randomuser.me/api/portraits/men/20.jpg",
    text: "I've had more valuable conversations here than anywhere else.",
  },
  {
    name: "Nadia Yusuf",
    role: "Graphic Designer",
    avatar: "https://randomuser.me/api/portraits/women/21.jpg",
    text: "Every interaction feels more authentic than traditional social media.",
  },
  {
    name: "Andrew Lewis",
    role: "Cybersecurity Analyst",
    avatar: "https://randomuser.me/api/portraits/men/22.jpg",
    text: "The platform encourages genuine curiosity and connection.",
  },
  {
    name: "Chloe Brown",
    role: "Copywriter",
    avatar: "https://randomuser.me/api/portraits/women/23.jpg",
    text: "I've met some of the most inspiring people through Poly.",
  },
  {
    name: "Ryan Mitchell",
    role: "DevOps Engineer",
    avatar: "https://randomuser.me/api/portraits/men/24.jpg",
    text: "It's a refreshing alternative to endless scrolling.",
  },
  {
    name: "Zainab Ali",
    role: "Researcher",
    avatar: "https://randomuser.me/api/portraits/women/25.jpg",
    text: "The sense of community here is unlike anything I've experienced.",
  },
  {
    name: "Nathan Scott",
    role: "Founder",
    avatar: "https://randomuser.me/api/portraits/men/26.jpg",
    text: "I connected with people who challenged and inspired me.",
  },
  {
    name: "Isabella Garcia",
    role: "Social Media Manager",
    avatar: "https://randomuser.me/api/portraits/women/27.jpg",
    text: "Poly makes building meaningful relationships effortless.",
  },
  {
    name: "Kevin Turner",
    role: "Backend Engineer",
    avatar: "https://randomuser.me/api/portraits/men/28.jpg",
    text: "The quality of people here keeps me coming back.",
  },
  {
    name: "Hannah Moore",
    role: "Teacher",
    avatar: "https://randomuser.me/api/portraits/women/29.jpg",
    text: "I found a supportive network within days of joining.",
  },
  {
    name: "Alex Morgan",
    role: "Creative Director",
    avatar: "https://randomuser.me/api/portraits/men/30.jpg",
    text: "It feels less like a platform and more like a real community.",
  },
];
